/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 */
@Schema(name="DictDetailVO",description="字典明细表")
@Entity(tableName="sqltoy_dict_detail",comment="字典明细表",pk_constraint="PRIMARY")
public abstract class AbstractDictDetailVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3528862261885504362L;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="dictKey",description="字典KEY",nullable=false)
	@Id
	@Column(name="DICT_KEY",comment="字典KEY",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String dictKey;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="dictType",description="字典类型代码",nullable=false)
	@Id
	@Column(name="DICT_TYPE",comment="字典类型代码",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String dictType;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="dictName",description="字典值",nullable=false)
	@Column(name="DICT_NAME",comment="字典值",length=200L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String dictName;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="showIndex",description="显示顺序",nullable=false)
	@Column(name="SHOW_INDEX",comment="显示顺序",length=8L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	protected Integer showIndex;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="updateBy",description="最后修改人",nullable=false)
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="status",description="状态",nullable=false)
	@Column(name="STATUS",comment="状态",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	protected Integer status;
	
	/** default constructor */
	public AbstractDictDetailVO() {
	}
	
	/** pk constructor */
	public AbstractDictDetailVO(String dictKey,String dictType)
	{
		this.dictKey=dictKey;
		this.dictType=dictType;
	}
	
	/**
	 *@param dictKey the dictKey to set
	 */
	public void setDictKey(String dictKey) {
		this.dictKey=dictKey;
	}
		
	/**
	 *@return the DictKey
	 */
	public String getDictKey() {
	    return this.dictKey;
	}
	
	/**
	 *@param dictType the dictType to set
	 */
	public void setDictType(String dictType) {
		this.dictType=dictType;
	}
		
	/**
	 *@return the DictType
	 */
	public String getDictType() {
	    return this.dictType;
	}
	
	/**
	 *@param dictName the dictName to set
	 */
	public void setDictName(String dictName) {
		this.dictName=dictName;
	}
		
	/**
	 *@return the DictName
	 */
	public String getDictName() {
	    return this.dictName;
	}
	
	/**
	 *@param showIndex the showIndex to set
	 */
	public void setShowIndex(Integer showIndex) {
		this.showIndex=showIndex;
	}
		
	/**
	 *@return the ShowIndex
	 */
	public Integer getShowIndex() {
	    return this.showIndex;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public Integer getStatus() {
	    return this.status;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("dictKey=").append(getDictKey()).append("\n");
		columnsBuffer.append("dictType=").append(getDictType()).append("\n");
		columnsBuffer.append("dictName=").append(getDictName()).append("\n");
		columnsBuffer.append("showIndex=").append(getShowIndex()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		return columnsBuffer.toString();
	}
	
}
