/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.callback.SelectFields;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import com.sqltoy.quickstart.vo.StaffInfoVO;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @version 1.0.0
 * Table: sqltoy_jsontype_showcae,Remark:JSON等特殊类型处理演示  
 */
@Entity(tableName="sqltoy_jsontype_showcae",pk_constraint="PRIMARY")
public abstract class AbstractJsontypeShowcaeVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1203577228088229819L;
	
	/**
	 * jdbcType:VARCHAR
	 * 主键ID
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String id;
	
	/**
	 * jdbcType:JSON
	 * 员工信息集合
	 */
	@Column(name="STAFF_SET",length=1073741824L,type=1021,nullable=false)
	protected List<StaffInfoVO> staffSet;
	
	/**
	 * jdbcType:DATETIME
	 * 创建日期
	 */
	@Column(name="CREATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:DATETIME
	 * 修改时间
	 */
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime updateTime;
	

	/** default constructor */
	public AbstractJsontypeShowcaeVO() {
	}
	
	/** pk constructor */
	public AbstractJsontypeShowcaeVO(String id)
	{
		this.id=id;
	}

	
	/**
	 *@param id the id to set
	 */
	public AbstractJsontypeShowcaeVO setId(String id) {
		this.id=id;
		return this;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param staffSet the staffSet to set
	 */
	public AbstractJsontypeShowcaeVO setStaffSet(List<StaffInfoVO> staffSet) {
		this.staffSet=staffSet;
		return this;
	}
		
	/**
	 *@return the StaffSet
	 */
	public List<StaffInfoVO> getStaffSet() {
	    return this.staffSet;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public AbstractJsontypeShowcaeVO setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
		return this;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public AbstractJsontypeShowcaeVO setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
		return this;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}



	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("id=").append(getId()).append("\n");
		columnsBuffer.append("staffSet=").append(getStaffSet()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		return columnsBuffer.toString();
	}
	
	/**
	 * @TODO create entityQuery fields
	 */
	public static SelectFieldsImpl select() {
		return new SelectFieldsImpl();
	}
	
	public static class SelectFieldsImpl extends SelectFields {
		private List<String> fields = new ArrayList<String>();

		@Override
		public String[] getSelectFields() {
			String[] result = new String[fields.size()];
			fields.toArray(result);
			return result;
		}
		
	    public SelectFieldsImpl id() {
	    	if (!fields.contains("id")) {
				fields.add("id");
			}
	    	return this;
	    }
    
	    public SelectFieldsImpl staffSet() {
	    	if (!fields.contains("staffSet")) {
				fields.add("staffSet");
			}
	    	return this;
	    }
    
	    public SelectFieldsImpl createTime() {
	    	if (!fields.contains("createTime")) {
				fields.add("createTime");
			}
	    	return this;
	    }
    
	    public SelectFieldsImpl updateTime() {
	    	if (!fields.contains("updateTime")) {
				fields.add("updateTime");
			}
	    	return this;
	    }
    
	}
	
	public static class Fields {
        /**
         * 主键ID
         */
    	public static String id="id";
    
        /**
         * 员工信息集合
         */
    	public static String staffSet="staffSet";
    
        /**
         * 创建日期
         */
    	public static String createTime="createTime";
    
        /**
         * 修改时间
         */
    	public static String updateTime="updateTime";
    
	}
}
