/**
 *@Generated by sagacity-quickvo 4.18
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import java.util.List;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.LocalDate;

/**
 * @project sqltoy-quickstart
 * @version 1.0.0
 * Table: sqltoy_trans_info_15d,Remark:支付交易流水表(15天表)  
 */
@Schema(name="TransInfo15dVO",description="支付交易流水表(15天表)")
@Entity(tableName="sqltoy_trans_info_15d",pk_constraint="PRIMARY")
public abstract class AbstractTransInfo15dVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5567949379312137039L;
	
	/**
	 * jdbcType:VARCHAR
	 * 交易ID
	 */
	@Schema(name="TRANS_ID",description="交易ID",nullable=false)
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="TRANS_ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String transId;
	
	/**
	 * jdbcType:VARCHAR
	 * 交易代码
	 */
	@Schema(name="TRANS_CODE",description="交易代码",nullable=false)
	@Column(name="TRANS_CODE",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String transCode;
	
	/**
	 * jdbcType:VARCHAR
	 * 交易渠道
	 */
	@Schema(name="TRANS_CHANNEL",description="交易渠道",nullable=false)
	@Column(name="TRANS_CHANNEL",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String transChannel;
	
	/**
	 * jdbcType:DECIMAL
	 * 交易金额
	 */
	@Schema(name="TRANS_AMT",description="交易金额",nullable=false)
	@Column(name="TRANS_AMT",length=14L,type=java.sql.Types.DECIMAL,nullable=false)
	protected BigDecimal transAmt;
	
	/**
	 * jdbcType:DECIMAL
	 * 交易状态
	 */
	@Schema(name="STATUS",description="交易状态",nullable=false)
	@Column(name="STATUS",length=1L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer status;
	
	/**
	 * jdbcType:VARCHAR
	 * 交易返回码
	 */
	@Schema(name="RESULT_CODE",description="交易返回码",nullable=false)
	@Column(name="RESULT_CODE",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String resultCode;
	
	/**
	 * jdbcType:DATETIME
	 * 交易时间
	 */
	@Schema(name="TRANS_TIME",description="交易时间",nullable=false)
	@Column(name="TRANS_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime transTime;
	
	/**
	 * jdbcType:DATE
	 * 交易日期
	 */
	@Schema(name="TRANS_DATE",description="交易日期",nullable=false)
	@Column(name="TRANS_DATE",length=10L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDate transDate;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户ID
	 */
	@Schema(name="USER_ID",description="用户ID",nullable=false)
	@Column(name="USER_ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String userId;
	
	/**
	 * jdbcType:VARCHAR
	 * 交易卡号
	 */
	@Schema(name="CARD_NO",description="交易卡号",nullable=true)
	@Column(name="CARD_NO",length=32L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String cardNo;
	

	/** default constructor */
	public AbstractTransInfo15dVO() {
	}
	
	/** pk constructor */
	public AbstractTransInfo15dVO(String transId)
	{
		this.transId=transId;
	}

	
	/**
	 *@param transId the transId to set
	 */
	public void setTransId(String transId) {
		this.transId=transId;
	}
		
	/**
	 *@return the TransId
	 */
	public String getTransId() {
	    return this.transId;
	}
	
	/**
	 *@param transCode the transCode to set
	 */
	public void setTransCode(String transCode) {
		this.transCode=transCode;
	}
		
	/**
	 *@return the TransCode
	 */
	public String getTransCode() {
	    return this.transCode;
	}
	
	/**
	 *@param transChannel the transChannel to set
	 */
	public void setTransChannel(String transChannel) {
		this.transChannel=transChannel;
	}
		
	/**
	 *@return the TransChannel
	 */
	public String getTransChannel() {
	    return this.transChannel;
	}
	
	/**
	 *@param transAmt the transAmt to set
	 */
	public void setTransAmt(BigDecimal transAmt) {
		this.transAmt=transAmt;
	}
		
	/**
	 *@return the TransAmt
	 */
	public BigDecimal getTransAmt() {
	    return this.transAmt;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public Integer getStatus() {
	    return this.status;
	}
	
	/**
	 *@param resultCode the resultCode to set
	 */
	public void setResultCode(String resultCode) {
		this.resultCode=resultCode;
	}
		
	/**
	 *@return the ResultCode
	 */
	public String getResultCode() {
	    return this.resultCode;
	}
	
	/**
	 *@param transTime the transTime to set
	 */
	public void setTransTime(LocalDateTime transTime) {
		this.transTime=transTime;
	}
		
	/**
	 *@return the TransTime
	 */
	public LocalDateTime getTransTime() {
	    return this.transTime;
	}
	
	/**
	 *@param transDate the transDate to set
	 */
	public void setTransDate(LocalDate transDate) {
		this.transDate=transDate;
	}
		
	/**
	 *@return the TransDate
	 */
	public LocalDate getTransDate() {
	    return this.transDate;
	}
	
	/**
	 *@param userId the userId to set
	 */
	public void setUserId(String userId) {
		this.userId=userId;
	}
		
	/**
	 *@return the UserId
	 */
	public String getUserId() {
	    return this.userId;
	}
	
	/**
	 *@param cardNo the cardNo to set
	 */
	public void setCardNo(String cardNo) {
		this.cardNo=cardNo;
	}
		
	/**
	 *@return the CardNo
	 */
	public String getCardNo() {
	    return this.cardNo;
	}



	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("transId=").append(getTransId()).append("\n");
		columnsBuffer.append("transCode=").append(getTransCode()).append("\n");
		columnsBuffer.append("transChannel=").append(getTransChannel()).append("\n");
		columnsBuffer.append("transAmt=").append(getTransAmt()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		columnsBuffer.append("resultCode=").append(getResultCode()).append("\n");
		columnsBuffer.append("transTime=").append(getTransTime()).append("\n");
		columnsBuffer.append("transDate=").append(getTransDate()).append("\n");
		columnsBuffer.append("userId=").append(getUserId()).append("\n");
		columnsBuffer.append("cardNo=").append(getCardNo()).append("\n");
		return columnsBuffer.toString();
	}
	
}
