/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 */
@Schema(name="SecureCaseVO",description="安全加解密演示")
@Entity(tableName="sqltoy_secure_case",comment="安全加解密演示",pk_constraint="PRIMARY")
public abstract class AbstractSecureCaseVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7970636119445180394L;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="staffId",description="工号",nullable=false)
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="STAFF_ID",comment="工号",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String staffId;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="staffName",description="姓名",nullable=false)
	@Column(name="STAFF_NAME",comment="姓名",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String staffName;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="telNo",description="移动电话",nullable=false)
	@Column(name="TEL_NO",comment="移动电话",length=500L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String telNo;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="telNoMask",description="电话检索",nullable=false)
	@Column(name="TEL_NO_MASK",comment="电话检索",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String telNoMask;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="homeAddress",description="家庭地址",nullable=false)
	@Column(name="HOME_ADDRESS",comment="家庭地址",length=500L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String homeAddress;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="homeAddressMask",description="家庭地址检索",nullable=false)
	@Column(name="HOME_ADDRESS_MASK",comment="家庭地址检索",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String homeAddressMask;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="createBy",description="创建人",nullable=false)
	@Column(name="CREATE_BY",comment="创建人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="createTime",description="创建时间",nullable=false)
	@Column(name="CREATE_TIME",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="updateBy",description="最后修改人",nullable=false)
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime updateTime;
	
	/** default constructor */
	public AbstractSecureCaseVO() {
	}
	
	/** pk constructor */
	public AbstractSecureCaseVO(String staffId)
	{
		this.staffId=staffId;
	}
	
	/**
	 *@param staffId the staffId to set
	 */
	public void setStaffId(String staffId) {
		this.staffId=staffId;
	}
		
	/**
	 *@return the StaffId
	 */
	public String getStaffId() {
	    return this.staffId;
	}
	
	/**
	 *@param staffName the staffName to set
	 */
	public void setStaffName(String staffName) {
		this.staffName=staffName;
	}
		
	/**
	 *@return the StaffName
	 */
	public String getStaffName() {
	    return this.staffName;
	}
	
	/**
	 *@param telNo the telNo to set
	 */
	public void setTelNo(String telNo) {
		this.telNo=telNo;
	}
		
	/**
	 *@return the TelNo
	 */
	public String getTelNo() {
	    return this.telNo;
	}
	
	/**
	 *@param telNoMask the telNoMask to set
	 */
	public void setTelNoMask(String telNoMask) {
		this.telNoMask=telNoMask;
	}
		
	/**
	 *@return the TelNoMask
	 */
	public String getTelNoMask() {
	    return this.telNoMask;
	}
	
	/**
	 *@param homeAddress the homeAddress to set
	 */
	public void setHomeAddress(String homeAddress) {
		this.homeAddress=homeAddress;
	}
		
	/**
	 *@return the HomeAddress
	 */
	public String getHomeAddress() {
	    return this.homeAddress;
	}
	
	/**
	 *@param homeAddressMask the homeAddressMask to set
	 */
	public void setHomeAddressMask(String homeAddressMask) {
		this.homeAddressMask=homeAddressMask;
	}
		
	/**
	 *@return the HomeAddressMask
	 */
	public String getHomeAddressMask() {
	    return this.homeAddressMask;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("staffId=").append(getStaffId()).append("\n");
		columnsBuffer.append("staffName=").append(getStaffName()).append("\n");
		columnsBuffer.append("telNo=").append(getTelNo()).append("\n");
		columnsBuffer.append("telNoMask=").append(getTelNoMask()).append("\n");
		columnsBuffer.append("homeAddress=").append(getHomeAddress()).append("\n");
		columnsBuffer.append("homeAddressMask=").append(getHomeAddressMask()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		return columnsBuffer.toString();
	}
	
}
