/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 */
@Schema(name="OrganInfoVO",description="机构信息表")
@Entity(tableName="sqltoy_organ_info",comment="机构信息表",pk_constraint="PRIMARY")
public abstract class AbstractOrganInfoVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7474501908084437190L;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="organId",description="机构ID",nullable=false)
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="ORGAN_ID",comment="机构ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String organId;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="organName",description="机构名称",nullable=false)
	@Column(name="ORGAN_NAME",comment="机构名称",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String organName;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="organCode",description="机构代码",nullable=false)
	@Column(name="ORGAN_CODE",comment="机构代码",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String organCode;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="costNo",description="成本中心代码",nullable=true)
	@Column(name="COST_NO",comment="成本中心代码",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String costNo;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="organPid",description="父机构ID",nullable=false)
	@Column(name="ORGAN_PID",comment="父机构ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String organPid;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="nodeRoute",description="节点路径",nullable=true)
	@Column(name="NODE_ROUTE",comment="节点路径",length=200L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String nodeRoute;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="nodeLevel",description="节点等级",nullable=true)
	@Column(name="NODE_LEVEL",comment="节点等级",length=1L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer nodeLevel;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="isLeaf",description="是否叶子节点",nullable=true)
	@Column(name="IS_LEAF",comment="是否叶子节点",length=1L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer isLeaf;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="showIndex",description="显示顺序",nullable=false)
	@Column(name="SHOW_INDEX",comment="显示顺序",length=8L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	protected Integer showIndex;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="createBy",description="创建人",nullable=false)
	@Column(name="CREATE_BY",comment="创建人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="createTime",description="创建时间",nullable=false)
	@Column(name="CREATE_TIME",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="updateBy",description="最后修改人",nullable=false)
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="status",description="状态",nullable=false)
	@Column(name="STATUS",comment="状态",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	protected Integer status;
	
	/** default constructor */
	public AbstractOrganInfoVO() {
	}
	
	/** pk constructor */
	public AbstractOrganInfoVO(String organId)
	{
		this.organId=organId;
	}
	
	/**
	 *@param organId the organId to set
	 */
	public void setOrganId(String organId) {
		this.organId=organId;
	}
		
	/**
	 *@return the OrganId
	 */
	public String getOrganId() {
	    return this.organId;
	}
	
	/**
	 *@param organName the organName to set
	 */
	public void setOrganName(String organName) {
		this.organName=organName;
	}
		
	/**
	 *@return the OrganName
	 */
	public String getOrganName() {
	    return this.organName;
	}
	
	/**
	 *@param organCode the organCode to set
	 */
	public void setOrganCode(String organCode) {
		this.organCode=organCode;
	}
		
	/**
	 *@return the OrganCode
	 */
	public String getOrganCode() {
	    return this.organCode;
	}
	
	/**
	 *@param costNo the costNo to set
	 */
	public void setCostNo(String costNo) {
		this.costNo=costNo;
	}
		
	/**
	 *@return the CostNo
	 */
	public String getCostNo() {
	    return this.costNo;
	}
	
	/**
	 *@param organPid the organPid to set
	 */
	public void setOrganPid(String organPid) {
		this.organPid=organPid;
	}
		
	/**
	 *@return the OrganPid
	 */
	public String getOrganPid() {
	    return this.organPid;
	}
	
	/**
	 *@param nodeRoute the nodeRoute to set
	 */
	public void setNodeRoute(String nodeRoute) {
		this.nodeRoute=nodeRoute;
	}
		
	/**
	 *@return the NodeRoute
	 */
	public String getNodeRoute() {
	    return this.nodeRoute;
	}
	
	/**
	 *@param nodeLevel the nodeLevel to set
	 */
	public void setNodeLevel(Integer nodeLevel) {
		this.nodeLevel=nodeLevel;
	}
		
	/**
	 *@return the NodeLevel
	 */
	public Integer getNodeLevel() {
	    return this.nodeLevel;
	}
	
	/**
	 *@param isLeaf the isLeaf to set
	 */
	public void setIsLeaf(Integer isLeaf) {
		this.isLeaf=isLeaf;
	}
		
	/**
	 *@return the IsLeaf
	 */
	public Integer getIsLeaf() {
	    return this.isLeaf;
	}
	
	/**
	 *@param showIndex the showIndex to set
	 */
	public void setShowIndex(Integer showIndex) {
		this.showIndex=showIndex;
	}
		
	/**
	 *@return the ShowIndex
	 */
	public Integer getShowIndex() {
	    return this.showIndex;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public Integer getStatus() {
	    return this.status;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("organId=").append(getOrganId()).append("\n");
		columnsBuffer.append("organName=").append(getOrganName()).append("\n");
		columnsBuffer.append("organCode=").append(getOrganCode()).append("\n");
		columnsBuffer.append("costNo=").append(getCostNo()).append("\n");
		columnsBuffer.append("organPid=").append(getOrganPid()).append("\n");
		columnsBuffer.append("nodeRoute=").append(getNodeRoute()).append("\n");
		columnsBuffer.append("nodeLevel=").append(getNodeLevel()).append("\n");
		columnsBuffer.append("isLeaf=").append(getIsLeaf()).append("\n");
		columnsBuffer.append("showIndex=").append(getShowIndex()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		return columnsBuffer.toString();
	}
	
}
