/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import com.sqltoy.quickstart.vo.StaffInfoVO;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 */
@Schema(name="JsontypeShowcaeVO",description="JSON等特殊类型处理演示")
@Entity(tableName="sqltoy_jsontype_showcae",comment="JSON等特殊类型处理演示",pk_constraint="PRIMARY")
public abstract class AbstractJsontypeShowcaeVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1203577228088229819L;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="id",description="主键ID",nullable=false)
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="ID",comment="主键ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String id;
	
	/**
	 * jdbcType:JSON
	 */
	@Schema(name="staffSet",description="员工信息集合",nullable=false)
	@Column(name="STAFF_SET",comment="员工信息集合",length=1073741824L,type=1021,nullable=false)
	protected List<StaffInfoVO> staffSet;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="createTime",description="创建日期",nullable=false)
	@Column(name="CREATE_TIME",comment="创建日期",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="updateTime",description="修改时间",nullable=false)
	@Column(name="UPDATE_TIME",comment="修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime updateTime;
	
	/** default constructor */
	public AbstractJsontypeShowcaeVO() {
	}
	
	/** pk constructor */
	public AbstractJsontypeShowcaeVO(String id)
	{
		this.id=id;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param staffSet the staffSet to set
	 */
	public void setStaffSet(List<StaffInfoVO> staffSet) {
		this.staffSet=staffSet;
	}
		
	/**
	 *@return the StaffSet
	 */
	public List<StaffInfoVO> getStaffSet() {
	    return this.staffSet;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("id=").append(getId()).append("\n");
		columnsBuffer.append("staffSet=").append(getStaffSet()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		return columnsBuffer.toString();
	}
	
}
