/**
 *@Generated by sagacity-quickvo 4.18
 */
package com.sqltoy.quickstart.vo.base;

import java.io.Serializable;
import java.util.List;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @version 1.0.0
 * Table: sqltoy_device_order,Remark:硬件购销定单表(演示有规则单号)  
 */
@Schema(name="DeviceOrderVO",description="硬件购销定单表(演示有规则单号)")
@Entity(tableName="sqltoy_device_order",pk_constraint="PRIMARY")
public abstract class AbstractDeviceOrderVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5912077678038173577L;
	
	/**
	 * jdbcType:VARCHAR
	 * 订单ID
	 */
	@Schema(name="ORDER_ID",description="订单ID",nullable=false)
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="ORDER_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String orderId;
	
	/**
	 * jdbcType:VARCHAR
	 * 设备类型
	 */
	@Schema(name="DEVICE_TYPE",description="设备类型",nullable=false)
	@Column(name="DEVICE_TYPE",length=10L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String deviceType;
	
	/**
	 * jdbcType:VARCHAR
	 * 购销标志
	 */
	@Schema(name="PS_TYPE",description="购销标志",nullable=false)
	@Column(name="PS_TYPE",length=10L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String psType;
	
	/**
	 * jdbcType:DECIMAL
	 * 商品总量
	 */
	@Schema(name="TOTAL_CNT",description="商品总量",nullable=true)
	@Column(name="TOTAL_CNT",length=12L,type=java.sql.Types.DECIMAL,nullable=true)
	protected BigDecimal totalCnt;
	
	/**
	 * jdbcType:DECIMAL
	 * 总金额
	 */
	@Schema(name="TOTAL_AMT",description="总金额",nullable=true)
	@Column(name="TOTAL_AMT",length=12L,type=java.sql.Types.DECIMAL,nullable=true)
	protected BigDecimal totalAmt;
	
	/**
	 * jdbcType:VARCHAR
	 * 购买方
	 */
	@Schema(name="BUYER",description="购买方",nullable=true)
	@Column(name="BUYER",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String buyer;
	
	/**
	 * jdbcType:VARCHAR
	 * 销售方
	 */
	@Schema(name="SALER",description="销售方",nullable=true)
	@Column(name="SALER",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String saler;
	
	/**
	 * jdbcType:DATE
	 * 成交日期
	 */
	@Schema(name="TRANS_DATE",description="成交日期",nullable=false)
	@Column(name="TRANS_DATE",length=10L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDate transDate;
	
	/**
	 * jdbcType:DATE
	 * 交货期限
	 */
	@Schema(name="DELIVERY_TERM",description="交货期限",nullable=true)
	@Column(name="DELIVERY_TERM",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDate deliveryTerm;
	
	/**
	 * jdbcType:VARCHAR
	 * 业务员
	 */
	@Schema(name="STAFF_ID",description="业务员",nullable=true)
	@Column(name="STAFF_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String staffId;
	
	/**
	 * jdbcType:VARCHAR
	 * 业务机构
	 */
	@Schema(name="ORGAN_ID",description="业务机构",nullable=true)
	@Column(name="ORGAN_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String organId;
	
	/**
	 * jdbcType:INT
	 * 状态
	 */
	@Schema(name="STATUS",description="状态",nullable=false)
	@Column(name="STATUS",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer status;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建人
	 */
	@Schema(name="CREATE_BY",description="创建人",nullable=false)
	@Column(name="CREATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Schema(name="CREATE_TIME",description="创建时间",nullable=false)
	@Column(name="CREATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 最后修改人
	 */
	@Schema(name="UPDATE_BY",description="最后修改人",nullable=false)
	@Column(name="UPDATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 最后修改时间
	 */
	@Schema(name="UPDATE_TIME",description="最后修改时间",nullable=false)
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime updateTime;
	

	/** default constructor */
	public AbstractDeviceOrderVO() {
	}
	
	/** pk constructor */
	public AbstractDeviceOrderVO(String orderId)
	{
		this.orderId=orderId;
	}

	
	/**
	 *@param orderId the orderId to set
	 */
	public void setOrderId(String orderId) {
		this.orderId=orderId;
	}
		
	/**
	 *@return the OrderId
	 */
	public String getOrderId() {
	    return this.orderId;
	}
	
	/**
	 *@param deviceType the deviceType to set
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType=deviceType;
	}
		
	/**
	 *@return the DeviceType
	 */
	public String getDeviceType() {
	    return this.deviceType;
	}
	
	/**
	 *@param psType the psType to set
	 */
	public void setPsType(String psType) {
		this.psType=psType;
	}
		
	/**
	 *@return the PsType
	 */
	public String getPsType() {
	    return this.psType;
	}
	
	/**
	 *@param totalCnt the totalCnt to set
	 */
	public void setTotalCnt(BigDecimal totalCnt) {
		this.totalCnt=totalCnt;
	}
		
	/**
	 *@return the TotalCnt
	 */
	public BigDecimal getTotalCnt() {
	    return this.totalCnt;
	}
	
	/**
	 *@param totalAmt the totalAmt to set
	 */
	public void setTotalAmt(BigDecimal totalAmt) {
		this.totalAmt=totalAmt;
	}
		
	/**
	 *@return the TotalAmt
	 */
	public BigDecimal getTotalAmt() {
	    return this.totalAmt;
	}
	
	/**
	 *@param buyer the buyer to set
	 */
	public void setBuyer(String buyer) {
		this.buyer=buyer;
	}
		
	/**
	 *@return the Buyer
	 */
	public String getBuyer() {
	    return this.buyer;
	}
	
	/**
	 *@param saler the saler to set
	 */
	public void setSaler(String saler) {
		this.saler=saler;
	}
		
	/**
	 *@return the Saler
	 */
	public String getSaler() {
	    return this.saler;
	}
	
	/**
	 *@param transDate the transDate to set
	 */
	public void setTransDate(LocalDate transDate) {
		this.transDate=transDate;
	}
		
	/**
	 *@return the TransDate
	 */
	public LocalDate getTransDate() {
	    return this.transDate;
	}
	
	/**
	 *@param deliveryTerm the deliveryTerm to set
	 */
	public void setDeliveryTerm(LocalDate deliveryTerm) {
		this.deliveryTerm=deliveryTerm;
	}
		
	/**
	 *@return the DeliveryTerm
	 */
	public LocalDate getDeliveryTerm() {
	    return this.deliveryTerm;
	}
	
	/**
	 *@param staffId the staffId to set
	 */
	public void setStaffId(String staffId) {
		this.staffId=staffId;
	}
		
	/**
	 *@return the StaffId
	 */
	public String getStaffId() {
	    return this.staffId;
	}
	
	/**
	 *@param organId the organId to set
	 */
	public void setOrganId(String organId) {
		this.organId=organId;
	}
		
	/**
	 *@return the OrganId
	 */
	public String getOrganId() {
	    return this.organId;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public Integer getStatus() {
	    return this.status;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}



	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("orderId=").append(getOrderId()).append("\n");
		columnsBuffer.append("deviceType=").append(getDeviceType()).append("\n");
		columnsBuffer.append("psType=").append(getPsType()).append("\n");
		columnsBuffer.append("totalCnt=").append(getTotalCnt()).append("\n");
		columnsBuffer.append("totalAmt=").append(getTotalAmt()).append("\n");
		columnsBuffer.append("buyer=").append(getBuyer()).append("\n");
		columnsBuffer.append("saler=").append(getSaler()).append("\n");
		columnsBuffer.append("transDate=").append(getTransDate()).append("\n");
		columnsBuffer.append("deliveryTerm=").append(getDeliveryTerm()).append("\n");
		columnsBuffer.append("staffId=").append(getStaffId()).append("\n");
		columnsBuffer.append("organId=").append(getOrganId()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		return columnsBuffer.toString();
	}
	
}
