/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sqltoy.quickstart.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractDeviceOrderVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_device_order,Remark:硬件购销定单表(演示有规则单号) 	
 */
@SqlToyEntity
public class DeviceOrderVO extends AbstractDeviceOrderVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5720676300522791730L;
	
	/** default constructor */
	public DeviceOrderVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DeviceOrderVO(String orderId)
	{
		this.orderId=orderId;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public DeviceOrderVO clone() {
		try {
			return (DeviceOrderVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
