/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sqltoy.quickstart.vo;

import java.util.List;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractDictTypeVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_dict_type,Remark:字典分类表 	
 */
@SqlToyEntity
public class DictTypeVO extends AbstractDictTypeVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7652087330184138442L;
	
	/** default constructor */
	public DictTypeVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DictTypeVO(String dictType)
	{
		this.dictType=dictType;
	}
	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public DictTypeVO clone() {
		try {
			return (DictTypeVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
