/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.sqltoy.quickstart.vo;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0 
 */
@Schema(name="DictDetailVO",description="字典明细表")
@Data
@Accessors(chain = true)
@Entity(tableName="sqltoy_dict_detail",comment="字典明细表",pk_constraint="PRIMARY")
public class DictDetailVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4263323295248169755L;
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="dictKey",description="字典KEY",nullable=false)
	@Id
	@Column(name="DICT_KEY",comment="字典KEY",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictKey;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="dictType",description="字典类型代码",nullable=false)
	@Id
	@Column(name="DICT_TYPE",comment="字典类型代码",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictType;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="dictName",description="字典值",nullable=false)
	@Column(name="DICT_NAME",comment="字典值",length=200L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictName;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="showIndex",description="显示顺序",nullable=false)
	@Column(name="SHOW_INDEX",comment="显示顺序",length=8L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer showIndex;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Schema(name="updateBy",description="最后修改人",nullable=false)
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Schema(name="status",description="状态",nullable=false)
	@Column(name="STATUS",comment="状态",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer status;
	
	/** default constructor */
	public DictDetailVO() {
	}
	
	/** pk constructor */
	public DictDetailVO(String dictKey,String dictType)
	{
		this.dictKey=dictKey;
		this.dictType=dictType;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
