/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.sqltoy.quickstart.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractJsontypeShowcaeVO;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_jsontype_showcae,Remark:JSON等特殊类型处理演示 	
 */
@SqlToyEntity
public class JsontypeShowcaeVO extends AbstractJsontypeShowcaeVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3425808763023689603L;
	
	/** default constructor */
	public JsontypeShowcaeVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public JsontypeShowcaeVO(String id)
	{
		this.id=id;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public JsontypeShowcaeVO clone() {
		try {
			return (JsontypeShowcaeVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
