/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.sqltoy.quickstart.vo;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0 
 */
@Schema(name="TransLedgerVO",description="交易台账并发演示表")
@Data
@Accessors(chain = true)
@Entity(tableName="sqltoy_trans_ledger",comment="交易台账并发演示表",pk_constraint="PRIMARY")
public class TransLedgerVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8988887096147387594L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Schema(name="id",description="ID",nullable=false)
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="ID",comment="ID",length=32L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=false)
	private String id;

	@Schema(name="orderId",description="订单ID",nullable=false)
	@Column(name="ORDER_ID",comment="订单ID",length=32L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=false)
	private String orderId;

	@Schema(name="quantity",description="数量",nullable=false)
	@Column(name="QUANTITY",comment="数量",length=10L,type=java.sql.Types.INTEGER,nativeType="INT",nullable=false)
	private Integer quantity;

	@Schema(name="amt",description="金额",nullable=false)
	@Column(name="AMT",comment="金额",length=12L,scale=2,type=java.sql.Types.DECIMAL,nativeType="DECIMAL",nullable=false)
	private BigDecimal amt;

	@Schema(name="createBy",description="创建人",nullable=false)
	@Column(name="CREATE_BY",comment="创建人",length=22L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=false)
	private String createBy;

	@Schema(name="createTime",description="创建时间",nullable=false)
	@Column(name="CREATE_TIME",comment="创建时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=false)
	private LocalDateTime createTime;

	@Schema(name="updateBy",description="最后修改人",nullable=false)
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=false)
	private String updateBy;

	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=false)
	private LocalDateTime updateTime;
	/** default constructor */
	public TransLedgerVO() {
	}
	
	/** pk constructor */
	public TransLedgerVO(String id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
