/**
 *@Generated by sagacity-quickvo 4.17
 */
package com.sqltoy.quickstart.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractTransShowcaseVO;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_trans_showcase,Remark:事务演示表 	
 */
@SqlToyEntity
public class TransShowcaseVO extends AbstractTransShowcaseVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6766542920890563658L;
	
	/** default constructor */
	public TransShowcaseVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public TransShowcaseVO(String id)
	{
		this.id=id;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public TransShowcaseVO clone() {
		try {
			return (TransShowcaseVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
