/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sqltoy.quickstart.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractTransInfoHisVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_trans_info_his,Remark:支付交易流水表 	
 */
@SqlToyEntity
public class TransInfoHisVO extends AbstractTransInfoHisVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1888897225560208297L;
	
	/** default constructor */
	public TransInfoHisVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public TransInfoHisVO(String transId)
	{
		this.transId=transId;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public TransInfoHisVO clone() {
		try {
			return (TransInfoHisVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
