/**
 *@Generated by sagacity-quickvo 4.17
 */
package com.sqltoy.quickstart.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import com.sqltoy.quickstart.vo.base.AbstractTransLedgerVO;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_trans_ledger,Remark:交易台账并发演示表 	
 */
@SqlToyEntity
public class TransLedgerVO extends AbstractTransLedgerVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8988887096147387594L;
	
	/** default constructor */
	public TransLedgerVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public TransLedgerVO(String id)
	{
		this.id=id;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public TransLedgerVO clone() {
		try {
			return (TransLedgerVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
